[2025-05-16T14:47:35.637+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdc_pipeline.check_consumer scheduled__2025-05-16T14:37:28.355202+00:00 [queued]>
[2025-05-16T14:47:35.816+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdc_pipeline.check_consumer scheduled__2025-05-16T14:37:28.355202+00:00 [queued]>
[2025-05-16T14:47:35.816+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2025-05-16T14:47:36.056+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): check_consumer> on 2025-05-16 14:37:28.355202+00:00
[2025-05-16T14:47:36.124+0000] {standard_task_runner.py:57} INFO - Started process 3473 to run task
[2025-05-16T14:47:36.131+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'cdc_pipeline', 'check_consumer', 'scheduled__2025-05-16T14:37:28.355202+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/cdc_pipeline_dag.py', '--cfg-path', '/tmp/tmpnqcn0gfw']
[2025-05-16T14:47:36.139+0000] {standard_task_runner.py:85} INFO - Job 118: Subtask check_consumer
[2025-05-16T14:47:36.538+0000] {task_command.py:415} INFO - Running <TaskInstance: cdc_pipeline.check_consumer scheduled__2025-05-16T14:37:28.355202+00:00 [running]> on host 2325534d36fc
[2025-05-16T14:47:37.353+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdc_pipeline' AIRFLOW_CTX_TASK_ID='check_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-05-16T14:37:28.355202+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-16T14:37:28.355202+00:00'
[2025-05-16T14:47:37.365+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-16T14:47:37.370+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'nc -z kafka-connect 8083 || (echo "Kafka Connect not running!" && exit 1)']
[2025-05-16T14:47:37.532+0000] {subprocess.py:86} INFO - Output:
[2025-05-16T14:47:37.570+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-16T14:47:37.821+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=cdc_pipeline, task_id=check_consumer, execution_date=20250516T143728, start_date=20250516T144735, end_date=20250516T144737
[2025-05-16T14:47:37.957+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-16T14:47:38.365+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
